FROM mongo:4.4

LABEL tech.tomy.docker.mongo="1.0"
LABEL maintainer="Tomy Hsieh @tomy0000000"

WORKDIR /

# Install envsbust
# RUN apt update
# RUN apt install -y gettext-base

# COPY config/mongod.conf /etc/mongod.conf
# COPY config/create_user.js create_user.js
# COPY config/init.sh init.sh
# RUN chmod +x init.sh

# ENTRYPOINT ["./init.sh"]
